#ifndef LIB_PINOCCIO_RADIO_H
#define LIB_PINOCCIO_RADIO_H

enum radio_state_t { RF_AWAKE = 0, RF_WILL_SLEEP, RF_SHOULD_SLEEP, RF_SLEEPING, RF_WILL_WAKE, RF_SHOULD_WAKE };

#endif // LIB_PINOCCIO_RADIO_H
